esphome:
  name: livingroom

esp8266:
  board: sonoff_th

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "McStar"
  password: "Fanno5euro!"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "DJOmZYUt9ZUA"

captive_portal:
    