from typing import Protocol, runtime_checkable


@runtime_checkable
class TemperatureSensor(Protocol):
    async def read_temperature(self) -> float: ...
    def device_id(self) -> str: ...


@runtime_checkable
class WindowSensor(Protocol):
    async def read_is_open(self) -> bool: ...
    def device_id(self) -> str: ...


@runtime_checkable
class BoilerController(Protocol):
    async def turn_on(self) -> None: ...
    async def turn_off(self) -> None: ...
    async def is_on(self) -> bool: ...
    def device_id(self) -> str: ...
